### ISSUE TITLE
Allow automatically expanding query body

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/aleph#40]
Can we add a flag to automatically expand the body object? That way the results of the CLI command on the image detail in Attribution Engine will be much more exciting!

Current output:

```
$ mcclient query -r QmeiY2eHMwK92Zt6X4kUUC3MsjMmVb2VnGZ17DhnhRPCEQ 'SELECT * FROM images.* WHERE wki = pexels_60224'

{ id: '4XTTM4K8sqTb7xYviJJcRDJ5W6TpQxMoJ7GtBstTALgh5wzGm:1476977626:4534031',
  publisher: '4XTTM4K8sqTb7xYviJJcRDJ5W6TpQxMoJ7GtBstTALgh5wzGm',
  namespace: 'images.pexels',
  body:
   { Body:
      { Simple:
         { object: 'QmYjqHCiRBF4zbTz3esm9ZVEEk8s7UqSeW1VZMQenAawwZ',
           refs: [ 'pexels_60224' ] } } },
  timestamp: 1476977626,
  signature: '1mQZlZ5ywm2LTQ6TSCK0g6kq8ozOhZdGSrHx6hFVB5sp2GKEdZMkpIWAWlIiIGtdvLCTvxD21ZSE6pJPQGHzBg==' }
```

**Comment by denisnazarov** [comment]
Any updates here?

**Comment by yusefnapora** [comment]
Yeah, sorry this didn't get in yesterday.  I should have it done in an hour or so.

**Comment by yusefnapora** [comment]
so this proved to be a little tricky, since fetching blobs from remote peers isn't implemented in the http api yet.  But I hacked the `getData` cli command to spin up an aleph node if you try to request data from a remote peer; it's hard-coded to use our public directory server, but I could make it query the concat node and use its configured directory server instead. 

Anyway, that works, so I should be able to use the same approach to get the blobs for query results.  I think that's the way to go, since we want people to be able to copy / paste commands from the web UI, so we shouldn't require them to merge data into their local store just to see it.

**Comment by parkan** [comment]
@denisnazarov ok so the short answer is that this will take a bit of work but we have a great solution
