### ISSUE TITLE
Don't require changing metadata object to specify WKI

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/aleph#52]
Moved from https://github.com/mediachain/concat/issues/70

Thinking through WKI specification while trying to write a [tutorial for writing MoMA data](https://gist.github.com/denisnazarov/f990f0e7367b38afa2bad351ee26d9a9) (credit to @yusefnapora ). It would be great to completely remove all the steps where you modify the original data.

We shouldn't require publishers to change their data to specify a WKI. Currently in our examples we're either adding prefixes to IDs (`dpla_abc123`) or new object keys (`MediachainWKI: "moma:artist:123""`from [the guide](https://gist.github.com/denisnazarov/f990f0e7367b38afa2bad351ee26d9a9)).

It would be elegant if publishers could keep their original metadata object completely untouched, giving nice properties such as keeping the same multihash if they're using the raw object somewhere else (like IPFS).

Can WKI prefixes be stored outside of the object? We already have a unique prefix we can automatically use: the namespace. Is this enough to avoid id collisions since, for example, MoMA uses integer IDs for artists and artworks.

We should also include searching by WKI more prominently in the docs!

**Comment by yusefnapora** [comment]
I definitely agree, and the WKIs are supposed to be stored in the `refs` field of the statement, not necessarily in the object itself.  The reason I had you add the WKI to the object was mostly because the jq-powered preprocessor isn't integrated into aleph yet, and the id extractor that's there now isn't quite up to snuff for the task.  Namely, it won't let you prepend a static prefix to an existing field and use the result as an ID.

I made a bit of progress on the jq front over the weekend, so I think we'll be able to use it soon.

**Comment by parkan** [comment]
Yeah, this is an implementation hack, they are not specified as being inside the object, don't look at this at all right now.

The prefixing happens when we write the WKI to the Statement, in the refs field here: https://github.com/mediachain/concat/blob/772a24f9f5c983b737277cb5d325828eb66ac1b0/proto/stmt.proto#L24

Gonna close this since we are on the way to handling this elsewhere.
